### ISSUE TITLE
Ajout système de logs

### ISSUE THREAD

**Issue by Refhi** [Refhi/Weda-Helper-Companion#11]
Comme la fenêtre Python n'est plus visible

**Comment by Abeldvlpr** [comment]
On peut rediriger les logs dans un fichier ou bien faire une fenêtre dans les options qui les affiche.
Sinon par défaut ils sont visible dans la console sur Mac, je ne sais pas où ils apparaissent sur Windows

**Comment by Refhi** [comment]
Fait dans la 1.4
