### ISSUE TITLE
Message erreur mise à jour

### ISSUE THREAD

**Issue by tpuszkarek** [Refhi/Weda-Helper-Companion#13]
Bonjour,
Désolé, question de novice : j'ai vu le changelog du compagnon et ai souhaité le mettre à jour.
Je suis sur PC au cabinet.
Il suffit de télécharger l'executable et de le lancer ?
J'ai ce message d'erreur :
 ![Capture5](https://github.com/Refhi/Weda-Helper-Companion/assets/158053494/47c78010-76b7-4147-be3a-aa949325b967)
Merci !

**Comment by Refhi** [comment]
Ah, probablement un soucis avec l'exécutable.
C'est bien Weda Companion.exe que tu as ？
Si oui je corrige ça ce soir

**Comment by tpuszkarek** [comment]
Oui, je l'ai téléchargé depuis le readme sur github :
![Capture](https://github.com/Refhi/Weda-Helper-Companion/assets/158053494/f73d93dc-916c-402d-b0f0-b510875bd857)
Rien ne presse ! Je pensais que le problème viendrait de moi.

**Comment by Refhi** [comment]
Corrigé !
Fichues dll....
