### ISSUE TITLE
Envoi au TPE défectueux au premier démarrage ?

### ISSUE THREAD

**Issue by Refhi** [Refhi/Weda-Helper-Companion#16]
Un peu compliqué à déboguer mais j'ai l'impression qu'au tout premier lancement l'impression fonctionnait mais pas le lien avec le TPE.
Fonctionnel après un redémarrage sans changement de paramètres.

Je peux te laisser jeter un œil vérifier que les paramètres par défaut soient bien pris en compte même avant un premier redémarrage stp ?

Merci :)

**Comment by Abeldvlpr** [comment]
En effet, ils n'étaient pas pris en compte dès le premier lancement, c'est résolu avec la dernière PR
