### ISSUE TITLE
Disparition des titres de consultation 

### ISSUE THREAD

**Issue by NadiaR01** [Refhi/Weda-Helper-Companion#17]
Bonjour,
 Merci beaucoup pour cette extension que je découvre petit à petit.
J'ai remarqué que je ne pouvais plus mettre de titre sur les consultations via le glossaire .
Peut être que cela a déjà été signalé (désolée pour le doublon) ?
Nadia

**Comment by Abeldvlpr** [comment]
Bonjour, il s’agit d’une options que vous pouvez désactiver en faisant un clic droit sur l’icône de l’extension et en cliquant sur « Options »

**Comment by Refhi** [comment]
Je me permets de fermer le ticket, n'hésitez pas si vous avez d'autres questions
