### ISSUE TITLE
Pas d'icône W dans la barre de système ( mais ca marche quand même ) 

### ISSUE THREAD

**Issue by OlivierSoussain** [Refhi/Weda-Helper-Companion#22]
![Capture d'écran 2024-06-28 091222](https://github.com/Refhi/Weda-Helper-Companion/assets/173998987/d06ff23e-b16e-43b1-b341-73e58ce8787d)

L'icône W du compagnon qui permet d'accéder au paramétrage ne se voit pas sur fond blanc. 
il n'est visible que sur fond noir ...

**Comment by Abeldvlpr** [comment]
Il est présent en regardant bien mais c’est blanc sur blanc.. je vais le modifier pour la prochaine version avec une icône plus contrastée

**Comment by OlivierSoussain** [comment]
![Capture d'écran 2024-06-28 091815](https://github.com/Refhi/Weda-Helper-Companion/assets/173998987/e3aeb9cf-e741-4309-9457-eebea71a951e)

**Comment by OlivierSoussain** [comment]
C'est exactement cela, je viens de m'en rendre compte.

**Comment by Philout14** [comment]
Pour ma part, je n'ai pas d'icône du helper companion dans la barre des taches... je laisse la fenetre d'execution active par contre... il y a d'autres solutions ? je l'aurais peut être mal installé ? Pourtant les impressions en Controle+P fonctionnent...

![Capture2](https://github.com/Refhi/Weda-Helper-Companion/assets/167795827/89922388-c79d-43d2-b686-eed4b2c9fea1)

**Comment by Abeldvlpr** [comment]
Bonjour, vous avez une ancienne version du companion. Vous pouvez télécharger la dernière version ici https://github.com/Refhi/Weda-Helper-Companion/releases/download/v1.4.3/Weda.Companion.exe

**Comment by Philout14** [comment]
Super merci, c'est ce que je viens de faire

**Comment by Abeldvlpr** [comment]
Fix dans [70120f9](https://github.com/Refhi/Weda-Helper-Companion/commit/70120f9953a0309e38ce646da5405a72a44b3fff)
