### ISSUE TITLE
Trojan ?

### ISSUE THREAD

**Issue by Philout14** [Refhi/Weda-Helper-Companion#24]
![Capture3](https://github.com/Refhi/Weda-Helper-Companion/assets/167795827/85ff824b-c765-4332-80f2-4cb69aa10597)
Après installation de la toute dernière version ce midi, Kaspersky détecte un Trojan dans le Companion ?

**Comment by Abeldvlpr** [comment]
Oui, c’est du aux outils utilisés pour faire fonctionner le Companion. Vous pouvez ajouter le fichier à la liste blanche sans inquiétude.

**Comment by Philout14** [comment]
C'est fait merci
