### ISSUE TITLE
dysfonctionnement du companion sur mac

### ISSUE THREAD

**Issue by dr-ranooo** [Refhi/Weda-Helper-Companion#25]
Comme je disais sur le blog, je ne parviens pas à faire fonctionner le companion sur mac. Je l'ai bien telechargé. J'ai cliqué sur ouvrir en contournant la securité du mac (clique droit sur l'appli et je reclique sur ouvrir). Elle semble s'activer mais après plus rien. Pas de logo en haut à droite de l'ecran à coté de vitalzen, pas weda companion qui tourne en arriere plan visible dans le moniteur d'activité et apparition d'un message d'erreur("[print] Impossible de joindre Weda-Helper-Companion : est-il bien paramétré et démarré ? Erreur: TypeError: Failed to fetch" ) quand je fais ctrl+P sur la page des prescriptions.
pourtant j'ai bien decoché l'option "Désactiver l'impression automatique complète via le companion (décocher pour l'activer)" dans weda helper. J'ai oublié quelque chose quelque part?

**Comment by Abeldvlpr** [comment]
Salut ! Est ce que tu es disponible pour que je fasse un TeamViewer sur ton ordinateur pour comprendre d’où cela vient ?

**Comment by dr-ranooo** [comment]
Oui je suis dispo
Mon tel est le 06 60 84 23 69

**Comment by Abeldvlpr** [comment]
@Refhi Cela venait d'un ancien format de préférences qui bloquait au lancement. J'ai rajouté des checks. J'ai fait un push de la 1.4.4 qui corrige ce problème, je te laisse vérifier quand tu as le temps et faire une release si tout te convient
