### ISSUE TITLE
connexion TPE

### ISSUE THREAD

**Issue by dr-ranooo** [Refhi/Weda-Helper-Companion#26]
rebonjour ;))
Le companion fonctionne j'arrive à imprimer avec ctrl+P. Merci +++
Je ne suis pas parvenue à connecter le TPE. J'ai bien trouvé l'adresse IP et le port. Mon prestataire de CB m'a confimé que j'avais bien trouvé les bonnes valeurs. Pour info, le port depend de sa banque et pas de l'appareil d'apres la personne que j'ai eu au telephone. Mais ca fonctionne pas pour autant...:'( J'ai testé les 2 protocoles.
Une idee? 
mon TPE se connecte à sa base par bluetooth et la base est connectée par ethernet. Le mode caisse est désactivé par défaut. Je l'ai activé pour voir mais ca change rien. Je ne sais pas comment fonctionne le companion pour choisir les bons parametres.

**Comment by Refhi** [comment]
Je crois qu'il va falloir qu'on fasse un FAQ sur cette thématique :-/

En pratique : 
- le protocole caisse DOIT être activé, en TCP/IP s'il le propose
- le port de connexion est - autant que je sache - dépendant du matériel et non de la banque
- si un ping vers l'IP de ton TPE fonctionne en théorie c'est bon signe (dans une console tu tapes ping [l'ip du TPE] puis entrée)
- certains TPE fonctionnent quand tu entres leur adresse IP dans le navigateur web, ça peut aider
- essaie aussi de désactiver quelques minutes ton firewall
- vérifie que ton routeur n'isole pas les différents périphériques présents sur ton réseau local

=> et il faut qu'on fasse https://github.com/Refhi/Weda-Helper/issues/173

**Comment by dr-ranooo** [comment]
Merci pour votre retour!!! 
J'ai reussi à le faire fonctionner! :))
j'ai activé la caisse
j'ai mis le port 8888 car mon TPE est ingenico (le conseiller qui gere le TPE ne m'a pas donné la bonne info!)
J'ai decouvert comment faire un ping sur mac (je suis contente d'apprendre des trucs et merci les tuto google) ce qui m'a confirmé que j'avais la bonne adresse IP
J'ai donné acces au bluetooth à weda companion dans les parametres de sécurité 
ET TADA! ça fonctionne
C'est clair il faudra un tuto pour les utilisateurs!
Merci encore, j'ai un nouveau joujou

**Comment by Refhi** [comment]
Cool 😎

Tu peux essayer de révoquer l'autorisation Bluetooth stp voire si on doit l'intégrer à la FAQ ? Merci d'avance 😊

**Comment by dr-ranooo** [comment]
et ben finalement en revoquant l'autorisation bluetooth, ca marche quand meme.  😅
