### ISSUE TITLE
problème clé API companion/weda helper

### ISSUE THREAD

**Issue by geflacroix** [Refhi/Weda-Helper-Companion#28]
Bonjour, tout d'abord je tiens à m'excuser je suis une vraie quiche en informatique alors il faut m'expliquer simplement et clairement, je ne comprends rien au jargon informatique... j'ai installé weda helper et companion mais quand je veux imprimer un document, cela me dit " Clé API non conforme. Vérifiez que la clé API des options de l'extension corresponde à la clé API des options du Companion". Or j'essaie depuis 3h de trouver comment voir la clé de Companion mais je n'y arrive pas. Quand je clique sur le fichier d'installation de Companion rien ne s'ouvre... Merci pour votre aide!
Gaëlle, sage-femme à Irigny (69)

**Comment by Abeldvlpr** [comment]
Bonjour, normalement si vous avez le companion installé, vous avez une icône W blanche dans la barre des tâches en bas à droite. En cliquant dessus vous accédez aux options du companion dans lesquelles se trouve la clef API.
Le plus simple et de supprimer ce qui est présent dans la ligne puis d’enregistrer les options. 
la clé sera automatiquement récupérée par le companion la prochaine fois que vous essayerez d’imprimer

**Comment by geflacroix** [comment]
il n'apparait pas dans la barre de taches malheureusement. Je n'arrête pas de redémarré mon ordi, désinstaller et réinstaller mais rien à faire.

**Comment by Abeldvlpr** [comment]
Avez vous bien la dernière version du companion ? Elle est telechargeable ici: https://github.com/Refhi/Weda-Helper-Companion/releases/download/v1.4.4/Weda.Companion.exe
Êtes vous sur Mac ou sur Windows ?

**Comment by geflacroix** [comment]
je viens de réinstaller en cliquant sur le lien que vous m'avez envoyé mais c'est toujours pareil. Je suis sur windows. J'ai désactivé le pare feu.

**Comment by Abeldvlpr** [comment]
Dans la barre des tâches en bas, même en cliquant sur la petite flèche vers le haut « ^ » vous ne voyez pas d’icône W blanche ?

**Comment by geflacroix** [comment]
ah ben après un énième redémarrage ça y est il apparait! j'ai mis la clé API mais maintenant ça me met "Erreur lors de l'impression du fichier PDF. Vérifiez que vous avez bien un logiciel d'impression PDF par défaut (Recommandé = Acrobat Reader)". J'ai ADOBE ACROBAT, ça va pas?

**Comment by geflacroix** [comment]
alléluia c'est bon ça marche!!! merci infiniment pour le temps que vous avez pris et d'avoir développé cet outil, je vais maintenant pouvoir l'explorer! bonne soirée, Gaëlle
