### ISSUE TITLE
liaison avec le TPE

### ISSUE THREAD

**Issue by elofr78** [Refhi/Weda-Helper-Companion#32]
Bonjour
je ne parviens pas à établir la liaison avec le TPE, pouvez-vous m'aider?
en vous remerciant,

**Comment by Fesco18** [comment]
How can I reach you

**Comment by Refhi** [comment]
Bonjour,

le lien avec le TPE est un poil technique à mettre en place, et nécessite pas mal de prérequis.
As-tu pu suivre les instructions du readme ? https://github.com/Refhi/Weda-Helper-Companion/blob/main/README.md#comment-activer-la-liaison-avec-le-tpe-

Sinon peux-tu préciser quelles étapes tu as déjà effectuées, si possible avec des captures d'écran ? (il faudrait aussi préciser le modèle de TPE)

**Comment by Ayiame** [comment]
Bonjour! Et un grand merci pour Weda Helper! 

Je relance ce ticket pour connaître les modalités de connexions du TPE. 
J'ai 2 IP de TPE sur mon INGENICO iwl250. Un port 9003 (section COMM_) , et un port 7019 (Section TMS/IP) affilié à chacune. J'essaie les 2, aucun résultat, le TPE est bien configuré en mode CAISSE.

TPE Bis ne donne pas de résultat. 

La commande http://localhost:4821/ fonctionne, mais pas [http://localhost:4821/log?apiKey=[cléapi]&versioncheck=1.2](http://localhost:4821/log?apiKey=%5Bcl%C3%A9api%5D&versioncheck=1.2) en changeant l'API. 

Quels sont les suites...? Merci!

**Comment by Refhi** [comment]
Bonjour,

merci pour l'encouragement, et toutes les précisions techniques :)

Si le ping de l'IP du TPE ne fonctionne pas, c'est un problème de configuration du réseau local. Je vous invite à contacter votre prestataire informatique ou le fournisseur du TPE :-/

N'hésitez pas à me tenir au courant,
