### ISSUE TITLE
Multi-fenêtres

### ISSUE THREAD

**Issue by NadiaR01** [Refhi/Weda-Helper-Companion#33]
Bonjour,
je viens de réinstaller Weda Helper et le companion, mais je n'ai plus les fenêtres de gauche (historiques des cs ). J'ai oublié de faire un truc ?
Merci

**Comment by Abeldvlpr** [comment]
Bonjour, c’est un bug qui va être corrigé, en attendant vous pouvez le corriger en créant un champ « IMC » dans les réglages de Weda sur les règles de suivi (TA, FC, poids, taille etc.)

**Comment by NadiaR01** [comment]
J'ai un peu honte... mais je ne sais pas créer un champ IMC

**Comment by Abeldvlpr** [comment]
Rendez vous dans le menu Paramètres > Mes préférences 
![Capture d'écran 2024-08-23 093532](https://github.com/user-attachments/assets/667a2916-da15-4669-9bdc-e70221eedd81)

Ajoutez une ligne "IMC" dans Valeurs de suivi par défaut et enregistrez en cliquant sur une des coches vertes.
![Capture d'écran 2024-08-23 093558](https://github.com/user-attachments/assets/159b6add-2d1d-4c68-88ce-1cbb87a29fc6)

**Comment by NadiaR01** [comment]
C'est fait, merci beaucoup !
