### ISSUE TITLE
problème téléchargement companion Mac

### ISSUE THREAD

**Issue by SpizzoAH** [Refhi/Weda-Helper-Companion#34]
Bonjour, 
Je viens de télécharger le companion pour Mac mais j'ai un message d'erreur qui m'emp^che de l'ouvrir. 
Il y a t il une solution pour contourner le problème? 
Je vous remercie pour votre aide et la réalisation de cet outil !! 

<img width="290" alt="Capture d’écran 2024-09-09 à 10 31 35" src="https://github.com/user-attachments/assets/bd75fa19-79d1-48d8-994b-901f462a45ba">

**Comment by Abeldvlpr** [comment]
Bonjour,

Comme indiqué sur la page principale du projet, il faut ouvrir le Companion en faisant un clic droit sur l'icone puis cliquer sur ouvrir au premier lancement.
