### ISSUE TITLE
Impossible de sélectionner le dossier "Corbeille" comme archive

### ISSUE THREAD

**Issue by Abeldvlpr** [Refhi/Weda-Helper-Companion#38]
A priori il y'a une restriction de sélection de dossier qui empêche de sélectionner la Corbeille comme dossier d'archive dans Windows...

On peut utiliser 'send2trash' à la place avec une case à cocher au lieu de la sélection d'un dossier d'archive

A faire avant la release 1.5 du Companion je pense

**Comment by Refhi** [comment]
j'ai aussi vu ce problème, que j'étais en train d'essayer d'ignorer ^^ (j'avais pas envie de retoucher à l'interface graphique)

si ça te va je veux bien te le laisser, tu es plus à l'aise que moi avec le Gui ?

sans rapport mais j'ai ajouté un bugfix pour contourner les pb de copie entre disques différents sous windows

**Comment by Abeldvlpr** [comment]
C'est implémenté !
Testé sur mac fonctionne nickel, je teste ca demain au cabinet sur PC

**Comment by Refhi** [comment]
bugfix fait pour windows, ça a l'air fonctionnel.
Je pense qu'on tient le bon bout !
Merci pour le GUI
Je peut te laisser recompiler pour mac, et on lance la release dans quelques jours si ça tiens bien ?

**Comment by Refhi** [comment]
je viens de pousser un fix car send2trash ne fonctionne pas depuis l'intérieur d'un .exe fait par pyinstaller >.<

**Comment by Abeldvlpr** [comment]
J'ai pas eu de soucis particulier avec la version compillée avant ton fix sur Windows. Tu avais bien installé send2trash avec pip avant la compilation ?

**Comment by Refhi** [comment]
ben pourtant oui :-/
et ça fonctionnait avant compilation, mais pas après !
Bref, le système passe maintenant par pywin qui fonctionne dans les deux cas...
Tu était bien sous win 11 pro ?
