### ISSUE TITLE
WEDA companion pour MAC

### ISSUE THREAD

**Issue by Solus-rgb** [Refhi/Weda-Helper-Companion#41]
**Décrivez le bug**
Weda companion ne peut pas être ouvert sur Mac " Faire une mise à jour car ne peut pas s'assurer qu'iln'y a pas de logiciel mal veillant

**Comment le reproduire**
Décrivez-moi les étapes pour reproduire le bug

**au besoin une capture d'écran (Maj+Win+S)**
Pensez à masquer les noms/prénom

**votre système**
 - OS: [e.g. iOS, mac, windows 11, etc.]
 - Navigateur web [e.g. chrome, safari, firefox]

**Comment by Refhi** [comment]
est-ce que https://github.com/Refhi/Weda-Helper-Companion#mac répond à ta problématique ?

**Comment by Solus-rgb** [comment]
Malheureusement, Mac refuse encore de l'ouvrir


Docteur Marine Le Duc-Solus
www.leduc-solus.com
Tel : 01 47 22 98 61
mobile: 06 18 07 83 82

**Comment by Refhi** [comment]
J'ai remis à jour la FAQ avec la solution que tu m'as envoyé par mail, merci beaucoup ☺️
