### ISSUE TITLE
bug lien weda compagnon windows

### ISSUE THREAD

**Issue by Dr-Vaucel** [Refhi/Weda-Helper-Companion#42]
bonjour hervé,

quand je fouille dans le readme du compagnon, le lien vers le compagnon met erreur 404 
![{3B1D60BE-197D-4000-B73B-E5EB5549ED72}](https://github.com/user-attachments/assets/cd1b7c28-1c34-4819-86e9-8298a0e0beb1)

**Comment by Abeldvlpr** [comment]
Bonjour, c'est corrigé !
