### ISSUE TITLE
Enregistrement auto de la clé API au premier request

### ISSUE THREAD

**Issue by Abeldvlpr** [Refhi/Weda-Helper-Companion#7]
Nous avons discuté d'éventuellement stocker la clef API lors du premier appel au Companion pour permettre aux utilisateurs de ne pas avoir à saisir celle-ci dans les options.

Est-ce qu'il ne vaudrais pas mieux retirer tout simplement la clef API ?
Sachant que nous n'acceptons déjà que des requests venant du localhost ce qui limite grandement la surface d'attaque et sachant que de toute façon nos requêtes entre l'extension et le Companion n'étant pas en HTTPS, la clef API est facilement interceptable et ne sert donc pas à grand chose à part rajouter de la friction à l'installation...
L'accès non authentifié au Companion nécessitant une execution depuis le localhost et ne donnant accès pour l'instant qu'a l'impression ou au TPE (qui est déjà accessible à n'importe qui sur le réseau d'ailleurs)

Je propose donc de la retirer tout simplement et de profiter de l'arrivée de l'interface utilisateur pour la retirer, sans que cela ne casse la compatibilité avec l'extension qui pourra continuer à la fournir sans que nous la verifions.

Si jamais ca te parais trop dangereux on peut partir sur l'idée de la récupérer lors de la première requête au Companion..

**Comment by Refhi** [comment]
Pour en avoir discuté avec mon frère, je préfère laisser tel quel, même si ça rajoute une manip initiale, ça incite aussi à aller voir dans les options.
Après si tu veux implémenter la récupération auto au premier lancement, ça me va aussi
J'ai ajouté un message dans les options
Est-ce que je peux te laisser compiler pour mac la dernière version et me l'envoyer stp ?
Merci :)

**Comment by Abeldvlpr** [comment]
Oui je comprends, je pense qu’on peut laisser tel quel pour le moment.
Je te compile ça quand je rentre de week-end

**Comment by Refhi** [comment]
Je ferme le ticket pour l'instant
pour la compil, n'hésite pas à attendre la 1.4 que je finalise probablement tout à l'heure

**Comment by Refhi** [comment]
Bon... après reflexion et discussion avec les utilisateurs, ça parait peut-être souhaitable en fait :-/
N'hésite pas à me dire si ça te tente de bosser sur la récupération auto de la clé (en gardant la possibilité de la modifier après coup)

**Comment by Abeldvlpr** [comment]
Je m’en charge !

**Comment by Refhi** [comment]
J'ai bien avancé dessus, est-ce que je peux te laisser tester ? (il suffit d'enregistrer un clé vide) et relancer une compil pour Mac ?

Merci :)

**Comment by Abeldvlpr** [comment]
Je t’avais fait une PR il y’a 2 jours 😬 #14

**Comment by Abeldvlpr** [comment]
L'avantage de ma PR étant qu'il n'y a pas besoin de valider une première fois les options pour que la clé API soit prise en compte

**Comment by Refhi** [comment]
Mince désolé 🙏 je suis passé à côté 😞
Je m'occupe de ta PR
Hésite pas à mettre tes PR dans les tickets au cas où je zappe 🫣

**Comment by Refhi** [comment]
Bon c'est réparé, j'ai remplacé mon commit par ta PR (d'ailleurs un reverse sur un PR est bien plus simple à reverse qu'un commit...)
Je peux te laisser recompiler stp ? (j'ai modifié le numéro de version)
merci :)

**Comment by Abeldvlpr** [comment]
Je te compile ça ce soir !

**Comment by Abeldvlpr** [comment]
C'est fait #15
